#!/bin/bash

if [ $# -eq 1 ]
then
    if [ $1 == c ] || [ $1 == C ]
    then
	mkdir obj src include
	cp /home/$USER/git/makefiles/c/Makefile .
    fi
else
    echo "Usage: projectInit <language>"
    echo "Languages supported:" 
    echo "    C/c"
fi