#!/bin/bash

# This file only saves 2 lines of typing currently, but is intended to make
# starting small projects faster by creating the directory tree +  other
# neccessities (for C a generic Makefile is included(see Makefiles))

if [ $# -eq 1 ]
then
    if [ $1 == c ] || [ $1 == C ]
    then
	mkdir obj src include
	cp /home/$USER/git/makefiles/c/Makefile .
    fi
else
    echo "Usage: projectInit <language>"
    echo "Languages supported:"
    echo "C/c"
fi