#!/bin/bash
# A script for automatically un-mounting a disk previously mounted with easymount
# again, as long as your labels are all unique, this should work fine
# goes togheter with easymount
#
# Usage: I have already brought myself to using easymount, so I can now unmount it by:
#    sudo easyumount <Disk label>
# 
# One nuisance is that "easymount" is not easier to type than "mount" :P
#    but you could make it "m" and "u"

if [ $# -eq 1 ]
then
    if [ -d /media/$1 ]
    then
	echo -ne '[###############               ](50%)\r'
	umount /media/$1
	rm -r /media/$1
	echo -ne '[##############################](100%)'
	echo "Done!"
    fi
else
    echo "Usage: easyumount <disk-by-label>"
fi

