#!/bin/bash

set -euxo pipefail

input=$1
input_noext=${input%.*}

echo $#

# PALLETTE # ffmpeg -i $input -vf fps=15,scale=320:-1:flags=lanczos,palettegen /tmp/palette.png

# defaults
fps=30
width=600

if [ "$#" -eq 2  ]; then
    fps=$2
elif [ "$#" -eq 3  ]; then
    fps=$2
    width=$3
fi

ffmpeg -v warning -i $input -filter_complex "fps=$fps,scale=$width:-1" -gifflags +transdiff -y $input_noext.gif
# PALLETTE # ffmpeg -i $input -i /tmp/palette.png -gifflags +transdiff -y \
# PALLETTE #     -filter_complex 'fps='$fps',scale='$width':-1:flags=lanczos[x];[x][1:v]paletteuse' $input_noext.gif

# PALLETTE # rm /tmp/palette.png
