#!/bin/zsh

cd /home/j/Media/Pictures/draws

source /home/j/.keychain/ripsoon-sh

inotifywait -m -e close_write,moved_to,create  . |
    while read -r directory events filename; do
        echo "filtering $filename on file extension..."
        if [[ "$filename" =~ ^.*\.\(jpg\|png\|gif\)$ ]]; then
            echo "rsyncing $filename..."
            rsync -av "$filename" pi:~/draws/to_process/
            rsync -av "$filename" imp:~/draws/to_process/
        fi
    done
