#!/bin/bash
set -euxo pipefail

# start a simple npm project! (template)

mkdir -p $1
cd $1
npm init -y
s_start="tsc -p . && node dist/main.js"
cat ./package.json \
    | jq --arg start "${s_start}" '.scripts |= . + {start: $start}' \
    > package.json.$$ \
    && mv package.json.$$ package.json

mkdir -p src

cat > tsconfig.json << EOM
{
    "compilerOptions": {
        "target" : "es5",
        "lib": ["dom", "es2018"],
        "strict": true,
        "outDir": "dist"
    }
}
EOM

cat > src/main.ts << EOM
console.log('hello, world!');
EOM

git init
echo "node_modules/" > .gitignore
