#!/bin/bash
set -euo pipefail

file='/tmp/screenshot/scrot.png'

cd /tmp/screenshot/
mkdir -p /tmp/screenshot
ffmpeg -y -video_size 3840x2160 -f x11grab -i :0.0 -vframes 1 -preset ultrafast $file
xclip -t image/png -selection clipboard -i < $file
feh -x --cycle-once --zoom fill -B black $file
