#!/bin/bash

# disable touch
xsetwacom set "Wacom Intuos Pro M Finger touch" Touch off

# multi monitor setup => map to 1 screen
#xsetwacom set "Wacom Intuos Pro M Pen stylus" MapToOutput HDMI
# xsetwacom set "Wacom Intuos Pro M Pen stylus" MapToOutput DVI-0

####################
# button setup
####################
                                                                # +-----------------
                                                                # |
                                                                # |  +--+
xsetwacom set "Wacom Intuos Pro M Pad pad" button 2 'key z'     # |  +--+
                                                                # |
                                                                # |  +--+
xsetwacom set "Wacom Intuos Pro M Pad pad" button 3 'key ctrl'  # |  +--+
                                                                # |
                                                                # |  +--+
xsetwacom set "Wacom Intuos Pro M Pad pad" button 8 'key shift' # |  +--+
                                                                # |
                                                                # |  +--+
xsetwacom set "Wacom Intuos Pro M Pad pad" button 9 'key e'     # |  +--+
                                                                # |
                                                                # |
xsetwacom set "Wacom Intuos Pro M Pad pad" RelWheelUp 0         # |      -------
xsetwacom set "Wacom Intuos Pro M Pad pad" AbsWheelUp 0         # |    -/       \-
                                                                # |   /   -----   \
xsetwacom set "Wacom Intuos Pro M Pad pad" button 1 'key m'     # |   |  (     )   |
                                                                # |   \   -----   /
xsetwacom set "Wacom Intuos Pro M Pad pad" RelWheelDown 0       # |    -\       /-
xsetwacom set "Wacom Intuos Pro M Pad pad" AbsWheelDown 0       # |      -------
                                                                # |
                                                                # |
                                                                # |  +--+
xsetwacom set "Wacom Intuos Pro M Pad pad" button 10 ''         # |  +--+
                                                                # |
                                                                # |  +--+
xsetwacom set "Wacom Intuos Pro M Pad pad" button 11 ''         # |  +--+
                                                                # |
                                                                # |  +--+
xsetwacom set "Wacom Intuos Pro M Pad pad" button 12 ''         # |  +--+
                                                                # |
                                                                # |  +--+
xsetwacom set "Wacom Intuos Pro M Pad pad" button 13 ''         # |  +--+
                                                                # |
                                                                # +-----------------
