#!/bin/bash

# disable touch
xsetwacom set "Wacom Intuos Pro S Finger touch" mode relative
xsetwacom set "Wacom Intuos Pro S (WL) Finger touch" mode relative
xsetwacom set "Wacom Intuos Pro S Finger touch" Touch off
xsetwacom set "Wacom Intuos Pro S (WL) Finger touch" Touch off

# multi monitor setup => map to 1 screen
# xsetwacom set "Wacom Intuos Pro S Pen stylus" MapToOutput LVDS-1
# xsetwacom set "Wacom Intuos Pro S (WL) Pen stylus" MapToOutput LVDS-1
xsetwacom set "Wacom Intuos Pro S Pen stylus" MapToOutput HDMI-1
xsetwacom set "Wacom Intuos Pro S (WL) Pen stylus" MapToOutput HDMI-1

####################
# button setup
####################
                                                                      # +-----------------
                                                                      # |
                                                                      # |  +--+
xsetwacom set "Wacom Intuos Pro S Pad pad" button 2 'key z'           # |  +  +
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" button 2 'key z'      # |  +--+
                                                                      # |
                                                                      # |  +--+
xsetwacom set "Wacom Intuos Pro S Pad pad" button 3 'key ctrl'        # |  +  +
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" button 3 'key ctrl'   # |  +--+
                                                                      # |
                                                                      # |  +--+
xsetwacom set "Wacom Intuos Pro S Pad pad" button 8 'key shift'       # |  +  +
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" button 8 'key shift'  # |  +--+
                                                                      # |
                                                                      # |
xsetwacom set "Wacom Intuos Pro S Pad pad" RelWheelUp 0               # |
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" RelWheelUp 0          # |
xsetwacom set "Wacom Intuos Pro S Pad pad" AbsWheelUp 0               # |      -------
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" AbsWheelUp 0          # |    -/       \-
                                                                      # |   /   -----   \
xsetwacom set "Wacom Intuos Pro S Pad pad" button 1 'key m'           # |   |  (     )   |
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" button 1 'key m'      # |   |  (     )   |
                                                                      # |   \   -----   /
xsetwacom set "Wacom Intuos Pro S Pad pad" RelWheelDown 0             # |    -\       /-
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" RelWheelDown 0        # |      -------
xsetwacom set "Wacom Intuos Pro S Pad pad" AbsWheelDown 0             # |
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" AbsWheelDown 0        # |
                                                                      # |
                                                                      # |
                                                                      # |  +--+
xsetwacom set "Wacom Intuos Pro S Pad pad" button 9  'key e'          # |  +  +
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" button 9  'key e'     # |  +--+
                                                                      # |
                                                                      # |  +--+
xsetwacom set "Wacom Intuos Pro S Pad pad" button 10 ''               # |  +  +
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" button 10 ''          # |  +--+
                                                                      # |
                                                                      # |  +--+
xsetwacom set "Wacom Intuos Pro S Pad pad" button 11 ''               # |  +  +
xsetwacom set "Wacom Intuos Pro S (WL) Pad pad" button 11 ''          # |  +--+
                                                                      # |
                                                                      # +-----------------
