#!/bin/bash
echo '<html><applet code='> appletLauncher.html
echo $1 >> appletLauncher.html
echo ' width="500" height="500"></applet></html>' >> appletLauncher.html
appletviewer appletLauncher.html
rm appletLauncher.html