#!/bin/bash

if [ $# -eq 1 ]
then
    if [ ! -d /media/$1 ]
    then
	mkdir -p /media/$1
    fi
    mount /dev/disk/by-label/$1 /media/$1
    cp -rub /home/$USER/important/ /media/$1/backups/
    umount /media/$1
    rm -r /media/$1
    echo "Done!"
elif [ $# -eq 2 ]
then
    if [ ! -d /media/$1 ]
    then
	mkdir -p /media/$1
    fi
    if [ -d /home/$USER/$2 ]
    then
	mount /dev/disk/by-label/$1 /media/$1
	cp -rub /home/$USER/$2/ /media/$1/backups/
	umount /media/$1
	rm -r /media/$1
	echo "Done!"
    else
	echo "DIR does not exist!"
    fi
else
    echo "Usage: backup <disk-by-label> [dir-in-home]"
    echo "if DIR is not specified, only important is backed up"
fi